# Generated by Django 6.0.7 on 2026-07-29 10:57

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('hex_code', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code, e.g. #FF5733.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_colors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlannerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot_interval', models.IntegerField(choices=[(30, '30 minutes'), (60, '60 minutes')], default=60)),
                ('day_start', models.TimeField(default=datetime.time(6, 0))),
                ('day_end', models.TimeField(default=datetime.time(0, 0))),
                ('time_format', models.CharField(choices=[('24h', '24-hour'), ('12h', '12-hour AM/PM')], default='24h', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=200)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_blocks', to='planner.blockcolor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('day_of_week', 'start_time'),
            },
        ),
        migrations.AddConstraint(
            model_name='blockcolor',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_block_color_name_per_user'),
        ),
    ]
