# Generated by Django 6.0.7 on 2026-08-08 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_timeblock_card_fields_activityevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrenceSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('partial', 'Partial'), ('completed', 'Completed'), ('incomplete', 'Incomplete'), ('abandoned', 'Abandoned'), ('transferred', 'Transferred')], default='planned', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('weekdays', models.JSONField(default=list)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrence_series', to='planner.blockcolor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_series', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('starts_on', 'start_time'),
            },
        ),
        migrations.AddField(
            model_name='timeblock',
            name='recurrence_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='planner.recurrenceseries'),
        ),
        migrations.CreateModel(
            name='RecurrenceException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurrence_date', models.DateField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='planner.recurrenceseries')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('series', 'occurrence_date'), name='unique_recurrence_exception_date')],
            },
        ),
    ]
