# Generated by Django 6.0.7 on 2026-08-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_recurrenceseries_timeblock_recurrence_series_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeblock',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
    ]
