# Generated by Django 6.0.7 on 2026-08-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_timeblock_skipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeblock',
            name='overridden',
            field=models.BooleanField(default=False),
        ),
    ]
