# Generated by Django 6.0.7 on 2026-08-08 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_timeblock_overridden'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=300)),
                ('is_completed', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('time_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='planner.timeblock')),
            ],
            options={
                'ordering': ('position', 'created_at', 'pk'),
                'indexes': [models.Index(fields=['time_block', 'position'], name='planner_che_time_bl_a8b363_idx')],
            },
        ),
    ]
