# Generated by Django 6.0.7 on 2026-08-08 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_checklistitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=2000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_comments', to=settings.AUTH_USER_MODEL)),
                ('time_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='planner.timeblock')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
    ]
