# Generated by Django 6.0.7 on 2026-08-08 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_cardcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='planner.cardcomment'),
        ),
    ]
