# Generated by Django 6.0.7 on 2026-08-08 16:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_cardcomment_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('hex_code', models.CharField(default='#64748B', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code, e.g. #FF5733.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_labels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='timeblock',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='cards', to='planner.cardlabel'),
        ),
        migrations.AddConstraint(
            model_name='cardlabel',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_card_label_name_per_user'),
        ),
    ]
