# Generated by Django 6.0.7 on 2026-08-08 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_cardtransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='planner.checklistitem'),
        ),
    ]
